name: isotope
description: A package of architecture libraries for modern Flutter applications.
version: 1.0.0
homepage: https://github.com/IsotopeLtd/isotope

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  apple_sign_in: ^0.1.0
  async: ^2.4.0
  collection: ^1.14.10
  convert: ^2.1.1
  file_access: ^1.0.3
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.3
  firebase_dynamic_links: ^0.5.0+9
  firebase_messaging: ^5.1.4
  firebase_storage: ^3.1.1
  flutter_facebook_login: ^3.0.0
  flutter_hooks: ^0.9.0
  flutter_secure_storage: ^3.3.1+1
  get: ^2.5.2
  google_sign_in: ^4.1.1
  http: ^0.12.0+2
  location: ^2.3.5
  meta: ^1.1.0
  package_info: ^0.4.0+13
  provider: ^4.0.5
  random_string: ^2.0.0
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
